  
[workspace]
members = [
    "web-todo",
    "libvlc",
    "opengl",
    "musicplayer",
    "gl_loader",
    "pixels",
    "wgpu",
    "framebuffer",
    "raqote",
    "plotters",
    "tinyskia",
    "systray",
]
