[package]
name = "pixels"
version = "0.1.0"
authors = ["Mohammed Alyousef <may642_2000@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "0.13.12"
pixels = "0.2.0"
env_logger = "0.7"
log = "0.4"