name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    
    steps:
    - name: Download deps
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev ninja-build libwebkit2gtk-4.0-dev
         fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Build ex1
      working-directory: calendar
      shell: bash
      run: cargo build --verbose
    - name: Build ex2
      run: cargo build --verbose
      working-directory: csv
      shell: bash
    - name: Build ex3
      run: cargo build --verbose
      working-directory: femtovg
      shell: bash
    - name: Build ex4
      run: cargo build --verbose
      working-directory: ffmpeg
      shell: bash
    - name: Build ex5
      run: cargo build --verbose
      working-directory: framebuffer
      shell: bash
    - name: Build ex6
      run: cargo build --verbose
      working-directory: glium
      shell: bash
    - name: Build ex7
      run: cargo build --verbose
      working-directory: glow
      shell: bash
    - name: Build ex8
      run: cargo build --verbose
      working-directory: glut
      shell: bash
    - name: Build ex9
      run: cargo build --verbose
      working-directory: image
      shell: bash
    - name: Build ex10
      run: cargo build --verbose
      working-directory: libvlc
      shell: bash
    - name: Build ex11
      run: cargo build --verbose
      working-directory: mpv
      shell: bash
    - name: Build ex12
      run: cargo build --verbose
      working-directory: musicplayer
      shell: bash
    - name: Build ex13
      run: cargo build --verbose
      working-directory: opengl
      shell: bash
    - name: Build ex14
      run: cargo build --verbose
      working-directory: pixels
      shell: bash
    - name: Build ex15
      run: cargo build --verbose
      working-directory: plotters
      shell: bash
    - name: Build ex16
      run: cargo build --verbose
      working-directory: raqote
      shell: bash
    - name: Build ex17
      run: cargo build --verbose
      working-directory: rounded-svg
      shell: bash
    - name: Build ex18
      run: cargo build --verbose
      working-directory: speedy2d
      shell: bash
    - name: Build ex19
      run: cargo build --verbose
      working-directory: systray
      shell: bash
    - name: Build ex20
      run: cargo build --verbose
      working-directory: tinyskia
      shell: bash
    - name: Build ex21
      run: cargo build --verbose
      working-directory: web-todo
      shell: bash
    - name: Build ex22
      run: cargo build --verbose
      working-directory: web-todo2
      shell: bash
    - name: Build ex23
      run: cargo build --verbose
      working-directory: webview
      shell: bash
    - name: Build ex24
      run: cargo build --verbose
      working-directory: wgpu
      shell: bash
    - name: Build ex25
      run: cargo build --verbose
      working-directory: xterm
      shell: bash
