name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    
    steps:
    - name: Download deps
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev ninja-build libwebkit2gtk-4.0-dev libvlc-dev libpango1.0-dev libpng-dev libgl1-mesa-dev libglu1-mesa-dev
         fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Build calendar
      working-directory: calendar
      shell: bash
      run: cargo build --verbose
    - name: Build csv
      run: cargo build --verbose
      working-directory: csv
      shell: bash
    - name: Build femtovg
      run: cargo build --verbose
      working-directory: femtovg
      shell: bash
    - name: Build ffmpeg
      run: cargo build --verbose
      working-directory: ffmpeg
      shell: bash
    - name: Build framebuffer
      run: cargo build --verbose
      working-directory: framebuffer
      shell: bash
    - name: Build glium
      run: cargo build --verbose
      working-directory: glium
      shell: bash
    - name: Build glow
      run: cargo build --verbose
      working-directory: glow
      shell: bash
    - name: Build glut
      run: cargo build --verbose
      working-directory: glut
      shell: bash
    - name: Build image
      run: cargo build --verbose
      working-directory: image
      shell: bash
    - name: Build libvlc
      run: cargo build --verbose
      working-directory: libvlc
      shell: bash
    - name: Build mpv
      run: cargo build --verbose
      working-directory: mpv
      shell: bash
    - name: Build musicplayer
      run: cargo build --verbose
      working-directory: musicplayer
      shell: bash
    - name: Build opengl
      run: cargo build --verbose
      working-directory: opengl
      shell: bash
    - name: Build pixels
      run: cargo build --verbose
      working-directory: pixels
      shell: bash
    - name: Build plotters
      run: cargo build --verbose
      working-directory: plotters
      shell: bash
    - name: Build raqote
      run: cargo build --verbose
      working-directory: raqote
      shell: bash
    - name: Build rounded-svg
      run: cargo build --verbose
      working-directory: rounded-svg
      shell: bash
    - name: Build speedy2d
      run: cargo build --verbose
      working-directory: speedy2d
      shell: bash
    - name: Build systray
      run: cargo build --verbose
      working-directory: systray
      shell: bash
    - name: Build tinyskia
      run: cargo build --verbose
      working-directory: tinyskia
      shell: bash
    - name: Build web-todo
      run: cargo build --verbose
      working-directory: web-todo
      shell: bash
    - name: Build web-todo2
      run: cargo build --verbose
      working-directory: web-todo2
      shell: bash
    - name: Build webview
      run: cargo build --verbose
      working-directory: webview
      shell: bash
    - name: Build wgpu
      run: cargo build --verbose
      working-directory: wgpu
      shell: bash
    - name: Build xterm
      run: cargo build --verbose
      working-directory: xterm
      shell: bash
